# Generated by Django 5.1.3 on 2024-11-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Loan',
            fields=[
                ('loan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=30)),
                ('loan_amd', models.FloatField()),
                ('cust_acno', models.IntegerField()),
                ('cust_name', models.CharField(max_length=50)),
            ],
        ),
    ]
